---

- hosts: all
  become: true
  tasks: 

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"
 
  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: remove httpd package
    yum:
      name: httpd
      state: absent
    when: ansible_distribution == "CentOS"

  - name: remove php support for httpd
    yum:
      name: php
      state: absent
    when: ansible_distribution == "CentOS"
